# Generated by Django 4.2 on 2024-11-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
    ]
