# Generated by Django 4.2 on 2024-12-02 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0003_publication_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='like',
        ),
        migrations.AddField(
            model_name='publication',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
