# Generated by Django 4.2 on 2024-12-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_like_publication_alter_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
